import { cloudClient } from './cloud/client'
import { cloud, special } from './cloud/data'

type Value = string | number | boolean | null | undefined

// Named application operations. SQL is used only by the explicitly selected local demo.
// Cloud requests use PostgREST's table API under PostgreSQL row-level security.
function operation<A extends Value[]>(method: 'query' | 'get' | 'run', sql: string, remote: (...args: A) => Promise<any>) {
  return (...args: A): Promise<any> => cloudClient
    ? remote(...args)
    : window.electronAPI.db[method](sql, args)
}

export const studyData = {
  listClasses: operation("query", "SELECT * FROM classes WHERE user_id = ? ORDER BY name", (userId: Value) => cloud.read('classes', { user_id: userId }, "name", false)),
  classNotes: operation("query", "SELECT * FROM notes WHERE user_id = ? AND class_id = ? ORDER BY updated_at DESC", (userId: Value, classId: Value) => cloud.read('notes', { user_id: userId, class_id: classId }, "updated_at DESC", false)),
  classCards: operation("query", "SELECT * FROM flashcards WHERE user_id = ? AND class_id = ? ORDER BY created_at DESC", (userId: Value, classId: Value) => cloud.read('flashcards', { user_id: userId, class_id: classId }, "created_at DESC", false)),
  classQuizzes: operation("query", "SELECT * FROM quizzes WHERE user_id = ? AND class_id = ? ORDER BY created_at DESC", (userId: Value, classId: Value) => cloud.read('quizzes', { user_id: userId, class_id: classId }, "created_at DESC", false)),
  createClass: operation("run", "INSERT INTO classes (user_id, name, color) VALUES (?, ?, ?)", (userId: Value, name: Value, color: Value) => cloud.insert('classes', { user_id: userId, name: name, color: color })),
  renameClass: operation("run", "UPDATE classes SET name = ?, color = ? WHERE id = ?", (name: Value, color: Value, id: Value) => cloud.update('classes', { name: name, color: color }, { id: id })),
  deleteClass: operation("run", "DELETE FROM classes WHERE id = ?", (id: Value) => cloud.remove('classes', { id: id })),
  countNotes: operation("query", "SELECT COUNT(*) as count FROM notes WHERE user_id = ?", (userId: Value) => cloud.count('notes', { user_id: userId }).then(value => [value])),
  countQuizzes: operation("query", "SELECT COUNT(*) as count FROM quizzes WHERE user_id = ?", (userId: Value) => cloud.count('quizzes', { user_id: userId }).then(value => [value])),
  countCards: operation("query", "SELECT COUNT(*) as count FROM flashcards WHERE user_id = ?", (userId: Value) => cloud.count('flashcards', { user_id: userId }).then(value => [value])),
  countSessions: operation("query", "SELECT COUNT(*) as count FROM pomodoro_sessions WHERE user_id = ? AND completed = 1", (userId: Value) => cloud.count('pomodoro_sessions', { user_id: userId, completed: true }).then(value => [value])),
  studyDates: operation("query", "SELECT DISTINCT DATE(completed_at, 'localtime') as study_date\n         FROM pomodoro_sessions\n         WHERE user_id = ? AND completed = 1\n         ORDER BY study_date DESC", (userId: Value) => special.studyDates(userId)),
  dailyFocus: operation("query", "SELECT COUNT(*) as sessions, COALESCE(SUM(duration_minutes), 0) as minutes\n           FROM pomodoro_sessions\n           WHERE user_id = ? AND completed = 1 AND DATE(completed_at, 'localtime') = ?", (userId: Value, date: Value) => special.dailyFocus(userId, date).then(value => [value])),
  listReminders: operation("query", "SELECT * FROM reminders WHERE user_id = ? ORDER BY priority ASC", (userId: Value) => cloud.read('reminders', { user_id: userId }, "priority ASC", false)),
  editReminder: operation("run", "UPDATE reminders SET title = ?, description = ?, date = ?, time = ?, color = ?, repeat = ?, completed = ?, updated_at = datetime('now') WHERE id = ?", (title: Value, description: Value, date: Value, time: Value, color: Value, repeat: Value, completed: Value, id: Value) => cloud.update('reminders', { title: title, description: description, date: date, time: time, color: color, repeat: repeat, completed: completed, updated_at: new Date().toISOString() }, { id: id })),
  lastReminderPriority: operation("get", "SELECT MAX(priority) as max FROM reminders WHERE user_id = ?", (userId: Value) => cloud.maximum('reminders', 'priority', { user_id: userId })),
  createReminder: operation("run", "INSERT INTO reminders (user_id, title, description, date, time, color, priority, repeat, completed, created_at, updated_at)\n           VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, datetime('now'), datetime('now'))", (userId: Value, title: Value, description: Value, date: Value, time: Value, color: Value, priority: Value, repeat: Value) => cloud.insert('reminders', { user_id: userId, title: title, description: description, date: date, time: time, color: color, priority: priority, repeat: repeat, completed: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() })),
  deleteReminder: operation("run", "DELETE FROM reminders WHERE id = ?", (id: Value) => cloud.remove('reminders', { id: id })),
  repeatReminder: operation("run", "UPDATE reminders SET date = ?, updated_at = datetime('now') WHERE id = ?", (date: Value, id: Value) => cloud.update('reminders', { date: date, updated_at: new Date().toISOString() }, { id: id })),
  completeReminder: operation("run", "UPDATE reminders SET completed = 1, updated_at = datetime('now') WHERE id = ?", (id: Value) => cloud.update('reminders', { completed: true, updated_at: new Date().toISOString() }, { id: id })),
  orderReminder: operation("run", "UPDATE reminders SET priority = ? WHERE id = ?", (priority: Value, id: Value) => cloud.update('reminders', { priority: priority }, { id: id })),
  listDecks: operation("query", "SELECT d.*, COUNT(f.id) as card_count\n         FROM flashcard_decks d\n         LEFT JOIN flashcards f ON f.deck_id = d.id\n         WHERE d.user_id = ?\n         GROUP BY d.id\n         ORDER BY d.created_at DESC", (userId: Value) => special.listDecks(userId)),
  noteSummaries: operation("query", "SELECT id, title, class_id, content FROM notes WHERE user_id = ? ORDER BY updated_at DESC", (userId: Value) => cloud.read('notes', { user_id: userId }, "updated_at DESC", false)),
  deckCards: operation("query", "SELECT * FROM flashcards WHERE deck_id = ? ORDER BY created_at ASC", (deckId: Value) => cloud.read('flashcards', { deck_id: deckId }, "created_at ASC", false)),
  deleteDeck: operation("run", "DELETE FROM flashcard_decks WHERE id = ?", (id: Value) => cloud.remove('flashcard_decks', { id: id })),
  createCard: operation("run", "INSERT INTO flashcards (user_id, deck_id, class_id, front, back, created_at) VALUES (?, ?, ?, ?, ?, datetime('now'))", (userId: Value, deckId: Value, classId: Value, front: Value, back: Value) => cloud.insert('flashcards', { user_id: userId, deck_id: deckId, class_id: classId, front: front, back: back, created_at: new Date().toISOString() })),
  deleteCard: operation("run", "DELETE FROM flashcards WHERE id = ?", (id: Value) => cloud.remove('flashcards', { id: id })),
  listNotes: operation("query", "SELECT * FROM notes WHERE user_id = ? ORDER BY updated_at DESC", (userId: Value) => cloud.read('notes', { user_id: userId }, "updated_at DESC", false)),
  createNote: operation("run", "INSERT INTO notes (user_id, class_id, title, content, created_at, updated_at)\n         VALUES (?, ?, ?, ?, datetime('now'), datetime('now'))", (userId: Value, classId: Value, title: Value, content: Value) => cloud.insert('notes', { user_id: userId, class_id: classId, title: title, content: content, created_at: new Date().toISOString(), updated_at: new Date().toISOString() })),
  getNote: operation("get", "SELECT * FROM notes WHERE id = ?", (id: Value) => cloud.read('notes', { id: id }, "id ASC", true)),
  listAttachments: operation("query", "SELECT * FROM note_attachments WHERE note_id = ? AND user_id = ? ORDER BY created_at DESC", (noteId: Value, userId: Value) => cloud.read('note_attachments', { note_id: noteId, user_id: userId }, "created_at DESC", false)),
  createAttachment: operation("run", "INSERT INTO note_attachments (note_id, user_id, filename, original_name, file_type, file_size, created_at)\n           VALUES (?, ?, ?, ?, ?, ?, datetime('now'))", (noteId: Value, userId: Value, filename: Value, originalName: Value, fileType: Value, fileSize: Value) => cloud.insert('note_attachments', { note_id: noteId, user_id: userId, filename: filename, original_name: originalName, file_type: fileType, file_size: fileSize, created_at: new Date().toISOString() })),
  deleteAttachment: operation("run", "DELETE FROM note_attachments WHERE id = ?", (id: Value) => cloud.remove('note_attachments', { id: id })),
  createQuiz: operation("run", "INSERT INTO quizzes (user_id, note_id, class_id, title, questions, created_at)\n         VALUES (?, ?, ?, ?, ?, datetime('now'))", (userId: Value, noteId: Value, classId: Value, title: Value, questions: Value) => cloud.insert('quizzes', { user_id: userId, note_id: noteId, class_id: classId, title: title, questions: questions, created_at: new Date().toISOString() })),
  latestNote: operation("get", "SELECT * FROM notes WHERE user_id = ? ORDER BY id DESC LIMIT 1", (userId: Value) => cloud.read('notes', { user_id: userId }, "id DESC", true, 1)),
  assignNoteClass: operation("run", "UPDATE notes SET class_id = ? WHERE id = ?", (classId: Value, id: Value) => cloud.update('notes', { class_id: classId }, { id: id })),
  attachmentFiles: operation("query", "SELECT filename FROM note_attachments WHERE note_id = ?", (noteId: Value) => cloud.read('note_attachments', { note_id: noteId }, "id ASC", false)),
  deleteNote: operation("run", "DELETE FROM notes WHERE id = ? AND user_id = ?", (id: Value, userId: Value) => cloud.remove('notes', { id: id, user_id: userId })),
  assignQuizClass: operation("run", "UPDATE quizzes SET class_id = ? WHERE id = ?", (classId: Value, id: Value) => cloud.update('quizzes', { class_id: classId }, { id: id })),
  listQuizzes: operation("query", "SELECT * FROM quizzes WHERE user_id = ? ORDER BY created_at DESC", (userId: Value) => cloud.read('quizzes', { user_id: userId }, "created_at DESC", false)),
  deleteQuizAttempts: operation("run", "DELETE FROM quiz_attempts WHERE quiz_id = ?", (quizId: Value) => cloud.remove('quiz_attempts', { quiz_id: quizId })),
  deleteQuiz: operation("run", "DELETE FROM quizzes WHERE id = ?", (id: Value) => cloud.remove('quizzes', { id: id })),
  saveQuizAttempt: operation("run", "INSERT INTO quiz_attempts (quiz_id, user_id, score, total, answers, completed_at) VALUES (?, ?, ?, ?, ?, datetime('now'))", (quizId: Value, userId: Value, score: Value, total: Value, answers: Value) => cloud.insert('quiz_attempts', { quiz_id: quizId, user_id: userId, score: score, total: total, answers: answers, completed_at: new Date().toISOString() })),
  quizHistory: operation("query", "SELECT qa.*, q.title as quiz_title, q.questions FROM quiz_attempts qa JOIN quizzes q ON qa.quiz_id = q.id WHERE qa.user_id = ? AND datetime(qa.completed_at) >= datetime(?) ORDER BY qa.completed_at DESC", (userId: Value, since: Value) => special.quizHistory(userId, since)),
  sessionHistory: operation("query", "SELECT * FROM pomodoro_sessions WHERE user_id = ? AND completed = 1 AND datetime(completed_at) >= datetime(?) ORDER BY completed_at DESC", (userId: Value, since: Value) => special.sessionHistory(userId, since)),
  saveSettings: operation("run", "UPDATE settings\n         SET theme = ?, dark_mode = ?, notification_sound = ?, timer_sound = ?,\n             pause_on_blur = ?, auto_resume_on_focus = ?, openai_api_key = ?, shortcuts = ?\n         WHERE user_id = ?", (theme: Value, darkMode: Value, notificationSound: Value, timerSound: Value, pauseOnBlur: Value, autoResumeOnFocus: Value, openaiApiKey: Value, shortcuts: Value, userId: Value) => cloud.update('settings', { theme: theme, dark_mode: darkMode, notification_sound: notificationSound, timer_sound: timerSound, pause_on_blur: pauseOnBlur, auto_resume_on_focus: autoResumeOnFocus, openai_api_key: openaiApiKey, shortcuts: shortcuts }, { user_id: userId })),
  getSettings: operation("get", "SELECT * FROM settings WHERE user_id = ?", (userId: Value) => cloud.read('settings', { user_id: userId }, "id ASC", true)),
  visibleStickyNotes: operation("query", "SELECT * FROM sticky_notes WHERE user_id = ? AND is_visible = 1", (userId: Value) => cloud.read('sticky_notes', { user_id: userId, is_visible: true }, "id ASC", false)),
  listStickyNotes: operation("query", "SELECT * FROM sticky_notes WHERE user_id = ? ORDER BY created_at DESC", (userId: Value) => cloud.read('sticky_notes', { user_id: userId }, "created_at DESC", false)),
  createStickyNote: operation("run", "INSERT INTO sticky_notes (user_id, content, position_x, position_y, color, is_visible)\n         VALUES (?, ?, ?, ?, ?, 1)", (userId: Value, content: Value, positionX: Value, positionY: Value, color: Value) => cloud.insert('sticky_notes', { user_id: userId, content: content, position_x: positionX, position_y: positionY, color: color, is_visible: true })),
  toggleStickyNote: operation("run", "UPDATE sticky_notes SET is_visible = ? WHERE id = ?", (isVisible: Value, id: Value) => cloud.update('sticky_notes', { is_visible: isVisible }, { id: id })),
  deleteStickyNote: operation("run", "DELETE FROM sticky_notes WHERE id = ?", (id: Value) => cloud.remove('sticky_notes', { id: id })),
  showStickyNotes: operation("run", "UPDATE sticky_notes SET is_visible = 1 WHERE user_id = ?", (userId: Value) => cloud.update('sticky_notes', { is_visible: true }, { user_id: userId })),
  hideStickyNotes: operation("run", "UPDATE sticky_notes SET is_visible = 0 WHERE user_id = ?", (userId: Value) => cloud.update('sticky_notes', { is_visible: false }, { user_id: userId })),
  saveTimerSettings: operation("run", "UPDATE settings SET pomodoro_work_minutes = ?, pomodoro_break_minutes = ?, pomodoro_long_break_minutes = ? WHERE user_id = ?", (pomodoroWorkMinutes: Value, pomodoroBreakMinutes: Value, pomodoroLongBreakMinutes: Value, userId: Value) => cloud.update('settings', { pomodoro_work_minutes: pomodoroWorkMinutes, pomodoro_break_minutes: pomodoroBreakMinutes, pomodoro_long_break_minutes: pomodoroLongBreakMinutes }, { user_id: userId })),
  dailyTimerStats: operation("query", "SELECT COUNT(*) as count, SUM(duration_minutes) as total_minutes\n         FROM pomodoro_sessions\n         WHERE user_id = ? AND completed = 1 AND DATE(completed_at, 'localtime') = ?", (userId: Value, date: Value) => special.dailyTimerStats(userId, date).then(value => [value])),
  saveNote: operation("run", "UPDATE notes SET title = ?, content = ?, class_id = ?, updated_at = datetime('now') WHERE id = ?", (title: Value, content: Value, classId: Value, id: Value) => cloud.update('notes', { title: title, content: content, class_id: classId, updated_at: new Date().toISOString() }, { id: id })),
  saveFocusSession: operation("run", "INSERT INTO pomodoro_sessions (user_id, duration_minutes, completed, completed_at)\n         VALUES (?, ?, 1, datetime('now'))", (userId: Value, durationMinutes: Value) => cloud.insert('pomodoro_sessions', { user_id: userId, duration_minutes: durationMinutes, completed: true, completed_at: new Date().toISOString() })),
}
